name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v2.1.0
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: f7f3120f-bf11-4558-b956-20b43a8d9924
