name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: checkout
        uses: actions/checkout@v2
      - name: measure coverage
        run: go test -v -coverprofile=coverage.out ./...
        working-directory: v2/
      - name: report coverage
        env:
          CODECOV_TOKEN: f7f3120f-bf11-4558-b956-20b43a8d9924
        working-directory: v2/
        run: |
          bash <(curl -s https://codecov.io/bash)
